/*
////////////////////////////////////////////////////////////////////////////////
// Создание таблицы студентов
////////////////////////////////////////////////////////////////////////////////
*/
CREATE TABLE STUDENTS 
(
  STUDENT_ID NUMBER(7, 0) NOT NULL,
  STUDENT_NAME VARCHAR2(40 BYTE) NOT NULL,
  STUDENT_GROUP VARCHAR2(7 BYTE) NOT NULL,
  STUDENT_GRANT NUMBER(7, 2)
);

ALTER TABLE STUDENTS
ADD CONSTRAINT STUDENTS_ID_PK PRIMARY KEY 
(
  STUDENT_ID 
)
ENABLE;

ALTER TABLE STUDENTS
ADD CONSTRAINT STUDENT_NAME_NN CHECK 
("STUDENT_NAME" IS NOT NULL)
ENABLE;

ALTER TABLE STUDENTS
ADD CONSTRAINT STUDENT_GROUP_NN CHECK 
("STUDENT_GROUP" IS NOT NULL)
ENABLE;

COMMENT ON COLUMN STUDENTS.STUDENT_ID IS 'Номер студенческого билета';

COMMENT ON COLUMN STUDENTS.STUDENT_NAME IS 'Имя студента';

COMMENT ON COLUMN STUDENTS.STUDENT_GROUP IS 'Группа студента';

COMMENT ON COLUMN STUDENTS.STUDENT_GRANT IS 'Стипендия студента';


/*
////////////////////////////////////////////////////////////////////////////////
// Создание таблицы зачеток
////////////////////////////////////////////////////////////////////////////////
*/
CREATE TABLE RECORDBOOKS 
(
  STUDENT_ID NUMBER(7, 0) NOT NULL
);

ALTER TABLE RECORDBOOKS
ADD CONSTRAINT STUDENT_ID_FK FOREIGN KEY
(
  STUDENT_ID 
)
REFERENCES STUDENTS
(
  STUDENT_ID 
)
ENABLE;

COMMENT ON COLUMN RECORDBOOKS.STUDENT_ID IS 'Номер студенческого билета';


/*
////////////////////////////////////////////////////////////////////////////////
// Создание таблицы предметов
////////////////////////////////////////////////////////////////////////////////
*/
CREATE TABLE SUBJECTS 
(
  SUBJECT_NAME VARCHAR2(20 BYTE) NOT NULL,
  SUBJECT_DATE DATE NOT NULL,
  SUBJECT_REPORTING_FORM VARCHAR2(20) NOT NULL,
  SUBJECT_GROUP VARCHAR2(7 BYTE) NOT NULL,
  SUBJECT_TEACHER_NAME VARCHAR2(40) NOT NULL 
);

ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECT_NAME_NN CHECK 
("SUBJECT_NAME" IS NOT NULL)
ENABLE;

ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECT_DATE_NN CHECK 
("SUBJECT_DATE" IS NOT NULL)
ENABLE;

ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECT_REPORTING_FORM_NN CHECK 
("SUBJECT_REPORTING_FORM" IS NOT NULL)
ENABLE;

ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECT_GROUP_NN CHECK 
("SUBJECT_GROUP" IS NOT NULL)
ENABLE;

ALTER TABLE SUBJECTS
ADD CONSTRAINT SUBJECT_TEACHER_NAME_NN CHECK 
("SUBJECT_TEACHER_NAME" IS NOT NULL)
ENABLE;
